env:
  browser: true
  es2021: true
  "jest/globals": true
extends:
  - eslint:recommended
  - prettier
  - plugin:@typescript-eslint/recommended
overrides: []
parser: "@typescript-eslint/parser"
plugins: ["jest", "@typescript-eslint"]
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  {
    quotes: ["error", "double"],
    no-underscore-dangle: ["off"],
    class-methods-use-this: ["off"],
  }
